---
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "cd server && docker build -t axw-digital/insight-admin ."
      - "cd server && docker tag axw-digital/insight-admin 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_admin"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_admin"
  pre_build: 
    commands: 
      - "echo Logging in to AWS..."
      - "docker login -u AWS -p eyJwYXlsb2FkIjoicnNGV3pIa1cwc0VjcWFISk93cG1YRWNvdGNRTFcrQ29HcVdtWTJhMjlGOFRyS0pSRm9XS3BrWjZpeHV1ZUt3b2FxRGtIWDZrOXBOQ3FTRWJvRlNOVGQrdUhqRlA4QXFXeGduNHFEK0I5UWVwYkZLdU02bkk2UjRvOEczeStRU3JFYll3cUlEMU1BUXRlN0VJNW9QUlV2dlc0Z0JodDRtd2FNR0tCTmRqTUEzbU5yT1pLYkpvMnFWcElOSmNuMkdxOHZobG5hSTBqdW1nL3lkcjJCRjhaZndnbGF6V0sxa1NDc1NkcFlaSXA2cTlIMmlEUTVrczNSalJVa1JlS3J0K1l2Tkc0MzRrVC9CaUtTZTJwZGpneVlGc3JhSnE2N0dTUGYvanhaQmp4VHhXTkt1VXRyM0Jkdy9NTndZaXoyQWhxcjVXRTkwb0l2MytnOUwwU3VrR09BT0FFazZVY21RUmMxMjNmb1U2UEhXTTVBK3dxZlJqTkxtNWFCMGRVY0RPZHNBck5tRWdOUzBsckQ2MHNuU01LOTdCTVVNK2pRd0lxWjVBVzJaYyt2cEVocDRIVXRpazlPS0ZTL2F4WEV2TjVDVTU0NUpuSlhxcm5mMzZZUFVFaEtWSWp3cjZWZitONFZuZldNa3hZbzMwZE5BeHlRY1BCZmtaQWpVZkdSQ0dHbjhFMysrV3dNNWZBZlJEQ0dVQ3hYT2hPeGY4SmRDdHRjZ3gxcW00MUxhQnkrNEdRdGJJbzBnRS9NZ3VSbnRadzN3Ty9CMlFqYlRsVXFIa2xJa2hqTUxNV0twcXhLLzREbGlURGNZZ2lZTVhmTGhxa3JaL1JWODloRHhjdmcxSUt4bEx6T29rbnJVRGc4S055RU1MbzBmazAyZ282QTJvVkI0WmIwbkc2WVpMbkNBOGJyWUJNclZraDVNT3dVeVN0TFNvSU53VHIwR1NiRGNGNkVtdTE0cEdWakRVVkJOd0pLdXhZSXFRNjhjMEpRWDFYM1p6cnAzV2Z0UnZKUU0rVEoyek9VSm1mdVRTZm50THlzcWtQM2dNSExKaytxTGU3K3UxaUZkNUhqZjFSRXVQQkpTTXJzNmhUSmpjNjlCWUt1TFkzdzJLRk9GeE9HcHJZOVdSNEFJZU1MWTV6Yi9XWU4vQmdWa3BMcmJZb2pqemovek5GQlRqL0Fvd0U4MFFPckxXQ250MHlENmFpVGVFalJuRWVaWFNDZkUyRVlSazVkS1VJWVBuSHlsSnZCN0hIUGx0cmRSWW1oMkN6RTBxY25nWDBidVczVm93TmhLR0RyUnUrdWdWMWR1VTcrRElrbWVuRUhuY1FRTitCTTl3TXI0T1A0c0c4MkJnZGpHSmR5MDV5bWVJN1RZSEppZnBPeXljVS9Cd3FETmdmVU4rdTgxejlIdkI0Yzd5UWFnTmtCelprVHpPNm5IOVBONGlQaSt6c2RYWmRyS3hSZUN4bmc9PSIsImRhdGFrZXkiOiJBUUlCQUhoZnJGUTJhSUl3RjVWYzc5UkhFUEduY1VXdXIyL0p6TTh0L1p6b0V0UnJBZ0hjME1Ndm5PMnRwcDdNNmhCRFRmSjRBQUFBZmpCOEJna3Foa2lHOXcwQkJ3YWdiekJ0QWdFQU1HZ0dDU3FHU0liM0RRRUhBVEFlQmdsZ2hrZ0JaUU1FQVM0d0VRUU10TU0xQThYcUNIYjNKaHljQWdFUWdEdXZ3Q2JJMXNZS3N1cEVoMzF5djhBTmZaK2xMcHMyeDExOVdLOGlBWGpYdjQzTk5ZQ0NQNnJaekVxcTI4amgxY3FGWUpoMnIvcnhKNU9ISUE9PSIsInZlcnNpb24iOiIyIiwidHlwZSI6IkRBVEFfS0VZIiwiZXhwaXJhdGlvbiI6MTYxODk1NDg4M30= 740126133497.dkr.ecr.eu-north-1.amazonaws.com"
artifacts:
  files: 
    - "**/*"
  name: "s3-to-s3-latest-build.zip" 
version: 0.1
